openai: 3.0.0
info: 
  title: Minha API simples
  version: 1.0.0
paths:
  /users:
    get:
      summary: Retorna todos os usuários
      responses:
        '200':
          description: Sucesso. Retorna uma lista de usuários.
        '500':
          description: Erro interno do servidor.
    post:
      summary: Adiciona um novo usuário
      requestBody:
        required: true
        content:
          application/json
            schema:
              type: objetct
              properties: 
                name:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
              required:
                - name
                - email
                - password
              responses:
              '200':
                description: Sucesso. O usuário foi adicionado com sucesso.
              '400':
                description: Dados inválidos. Veja os erros para mais destalhes.
              '500':
                description: Erro interno do servidor.